---
title: "Retirement Projection"
author: "Jeff Li"
date: "12/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Set dir from which to read in expense file
knitr::opts_knit$set(root.dir='~/GitHub/Retirement_Planning')
setwd("~/GitHub/Retirement_Planning")

library(dplyr)
library(ggplot2)
library(lubridate)
library(scales)
library(knitr)
library(kableExtra)
options(scipen=999)

```


```{r initialization, echo=FALSE, include=FALSE}

source('code/1_libraries_load.R')
source('code/2_user_def_funcs_load.R')
source('code/3_initial_inputs.R')

#Import s&p500 returns file
sp_500_returns <- fread(sp_500_filepath, header=TRUE)
setnames(sp_500_returns, names(sp_500_returns))

print(names(sp_500_returns))

```


```{r inputs, echo=FALSE}

# Simulation Inputs Configurations
######################################################################################################################

# Expected contribution dollar amount by month
contribution_by_period <- (curr_salary * (contrib_401k_perc + company_401k_match_perc) + annual_ira_contribution) / 12

# Number of months before retirement age
age_in_months <- length(seq(from=as.Date(birth_date, '%M/%d/%Y'), to=as.Date(init_date, '%M/%d/%Y'), by='month'))
months_till_retirement <- target_retirement_age*12 - age_in_months
contrib_period_count <- months_till_retirement

# Expected initial withdraw rate at retirement in order to achieve targeted income level at current cost of living
target_retirement_income_fv <- target_retirement_income_lvl*((1+annual_withdraw_increase_perc)^(months_till_retirement/12))
init_withdraw_target <- target_retirement_income_fv / 12
withdraw_period_count <- life_expectancy*12 - target_retirement_age*12

# Input Info Table Creation
input_age_nms <- c('Current Age', 'Target Retirement Age', 'Life Expectancy')
input_age_data <- c(round(age_in_months/12), target_retirement_age, life_expectancy)
input_age_table <- cbind.data.frame(input_age_nms, input_age_data)
names(input_age_table) <- c('Age_Category', 'Age_Data')

input_dollar_nms <- c('Starting Retirement Principal', 'Current Salary', 'Annual IRA Contribution',
                      "Target Annual Retirement Income (In Today's Dollars)")
input_dollar_data <- c(init_principle, curr_salary, annual_ira_contribution, target_retirement_income_lvl)
input_dollar_table <- cbind.data.frame(input_dollar_nms, input_dollar_data)
names(input_dollar_table) <- c('Dollar_Category','Dollar_Data')
input_dollar_table$Dollar_Data <- dollar(input_dollar_table$Dollar_Data)

# Assumption Table Creation
input_perc_nms <- c('Current 401K Contribution Percentage','401K Company Match Percentage',
                    'Annual Contribution Increase Percentage', 'Expected Inflation', 'Assumed Average Return (Pre-Retirement)',
                    'Assumed Average Return (Post-Retirement)')
input_perc_data <- c(contrib_401k_perc, company_401k_match_perc, annual_contribution_increase_perc, 
                     annual_withdraw_increase_perc, assumed_avg_return_pre_retirement, assumed_avg_return_post_retirement)
input_perc_table <- cbind.data.frame(input_perc_nms, input_perc_data)
names(input_perc_table) <- c('Percentage_Category', 'Percentage_Data')
input_perc_table$Percentage_Data <- percent(input_perc_table$Percentage_Data)


```

***
## Inputs / Assumptions

```{r results='asis', echo=FALSE}

#t1 <- knitr::kable(input_table, format='html', table.attr='cellspacing="10"', output=FALSE, caption="Inputs Information")
#t2 <- knitr::kable(assum_table, format='html', table.attr='cellspacing="10"', output=FALSE, caption='Assumptions')
#cat(c('<table><tr valign="top"><td>', t1, '</td>', '<td>', t2, '</td></tr></table>'),
#    sep = '')
#cat(c("\\begin{table}[h] \\centering ", t1, "\\hspace{1cm} \\centering ", t2, 
#      "\\caption{My tables} \\end{table}"))

#knitr::kable(list(input_table, assum_table), caption='test')

input_age_table %>% kable() %>% kable_styling(bootstrap_options=c('bordered','striped','condensed','responsive'),
                                          full_width=FALSE, position='center')

input_dollar_table %>% kable() %>% kable_styling(bootstrap_options=c('bordered','striped','condensed','responsive'),
                                          full_width=FALSE, position='float_left')

input_perc_table %>% kable() %>% kable_styling(bootstrap_options=c('bordered','striped','condensed','responsive'),
                                          full_width=FALSE, position='right')

#cat(c("\\begin{table}[h] \\centering ", input_table, "\\hspace{1cm} \\centering ", assum_table, 
#      "\\caption{My tables} \\end{table}"))

#kable(
#  list(
#    input_table,
#    assum_table
#  ),
#  caption = 'Two tables placed side by side.',
#  booktabs = TRUE, valign = 't'
#) %>% kable_styling(bootstrap_options=c('bordered','striped','condensed','responsive'),
#                                          full_width=FALSE, position='right')

```


```{r simulation, echo=FALSE}

# Retirement Nest Egg Accumulation Schedule Projections
######################################################################################################################

curr_dt <- init_date
P=init_principle
c=contribution_by_period
c_annual_incr=annual_contribution_increase_perc
c_mthly_incr=(1+c_annual_incr)^(1/12)-1
n=contrib_period_count

return_scenarios_rng <- return_scenario_gen(sp_500_returns, n, perc_rng=c(0.05, 0.95))

annual_rate=assumed_avg_return_pre_retirement
mthly_rate <- (1+annual_rate)^(1/12)-1
annuity_accum_table <- annuity_fv(curr_dt, P, n, c, c_mthly_incr, mthly_rate)

annuity_accum_table_opti <- annuity_fv_v2(curr_dt, P, n, c, c_mthly_incr, return_scenarios_rng[[1]])
annuity_accum_table_pess <- annuity_fv_v2(curr_dt, P, n, c, c_mthly_incr, return_scenarios_rng[[2]])

annuity_accum_rng <- cbind.data.frame('date'=annuity_accum_table$date, 
                                      'tot_opti'=annuity_accum_table_opti$tot, 'tot_pess'=annuity_accum_table_pess$tot)



# Retirement Nest Egg Withdraw Schedule Projections
######################################################################################################################

retire_dt <- annuity_accum_table$date[nrow(annuity_accum_table)]
P=annuity_accum_table$tot[nrow(annuity_accum_table)]
P_opti=annuity_accum_table_opti$tot[nrow(annuity_accum_table_opti)]
P_pess=annuity_accum_table_pess$tot[nrow(annuity_accum_table_pess)]
c=init_withdraw_target
annual_rate=assumed_avg_return_post_retirement
annual_inflation=annual_withdraw_increase_perc
mthly_rate <- (1+annual_rate)^(1/12)-1
mthly_inflation <- (1+annual_inflation)^(1/12)-1
m <- withdraw_period_count

amort_withdraw_table <- amort_sched(retire_dt, P, c, mthly_rate, mthly_inflation, m)

amort_withdraw_table_opti <- amort_sched(retire_dt, P_opti, c, mthly_rate, mthly_inflation, m)
amort_dispersion_table_opti <- amort_withdraw_table_opti %>% mutate(remain_prin_opti=remain_prin) %>% select(date, remain_prin_opti)

amort_withdraw_table_pess <- amort_sched(retire_dt, P_pess, c, mthly_rate, mthly_inflation, m)
amort_dispersion_table_pess <- amort_withdraw_table_pess %>% mutate(remain_prin_pess=remain_prin) %>% select(date, remain_prin_pess)

amort_dispersion_rng <- merge(amort_dispersion_table_opti, amort_dispersion_table_pess, by='date', all=TRUE)
amort_dispersion_rng %<>% mutate(remain_prin_pess=ifelse(is.na(remain_prin_pess),0,remain_prin_pess))


```


***
## Retirement Projection {.tabset .tabset-fade .tabset-pills}

###  Principal Accumulation and Distribution

Chart below reflects retirement accumulation as well as distribution projections based on above inputs and assumptions.


```{r plotting, echo=FALSE, warning=FALSE}

# Retirement Projection Plotting 
#######################################################################################################################

overall_proj_table <- merge(annuity_accum_table, amort_withdraw_table, by='date', all=TRUE)
overall_proj_table <- merge(overall_proj_table, annuity_accum_rng, by='date', all=TRUE)
overall_proj_table <- merge(overall_proj_table, amort_dispersion_rng, by='date', all=TRUE)
overall_proj_table <- merge(overall_proj_table, actual_table, by='date', all=TRUE)

cutoff_yr <- 2090
plot_data <- overall_proj_table %>% filter(year(overall_proj_table$date) <= cutoff_yr)

plot <- ggplot()
plot <- plot + geom_line(data=plot_data, aes(x=date, y=tot), size=1, colour='springgreen4') 
plot <- plot + geom_line(data=plot_data, aes(x=date, y=remain_prin), size=1, colour='red')
plot <- plot + geom_ribbon(data=plot_data, aes(x=date, ymin=tot_pess, ymax=tot_opti), fill='springgreen4', alpha=0.2)
plot <- plot + geom_ribbon(data=plot_data, aes(x=date, ymin=remain_prin_pess, ymax=remain_prin_opti), fill='red', alpha=0.2)
plot <- plot + geom_point(data=plot_data, aes(x=date, y=accum_amt), colour='navy')
#plot <- plot +  scale_x_date(date_breaks = '5 year', date_labels='%Y') + theme(axis.text.x = element_text(angle=45, hjust=1, size=7)) 
plot <- plot +  scale_x_date(date_labels='%b-%Y') + theme(axis.text.x = element_text(angle=45, hjust=1, size=7)) 
plot <- plot +  labs(title='Retirement Nestegg Projection', x="Date", y="Total Accumulated Amount($)") 

plot

```

### Annual Retirement Income Levels

```{r ret_income, echo=FALSE, warning=FALSE}

retire_yrs <- floor(nrow(amort_withdraw_table) / 12)
retire_yrs_key <- cut(c(1:nrow(amort_withdraw_table)), breaks=seq(0,nrow(amort_withdraw_table),12), labels=c(1:retire_yrs))

withdraw_lvls <- cbind.data.frame(amort_withdraw_table, retire_yrs_key)
withdraw_lvls %<>% group_by(retire_yrs_key) %>% summarise(annual_income_lvl=round(sum(withdraw_amt))) %>% 
  filter(!(is.na(retire_yrs_key)))
withdraw_lvls

plot(withdraw_lvls)


```